### ISSUE TITLE
Theme.ini Configuration Problems

### ISSUE THREAD

**Issue by raven2cz** [baumgarr/nixnote2#296]
I'm testing theme.ini configuration. Mainly the dark theme modifications for KDE Dark Breeze (standard theme of KDE). 
The parameters `editorBackgroundColor=white` and `editorFontColor=black` doesn't work.

I have to modify css file and configure theme like this` /usr/share/nixnote2/qss/editor_light.css` and use this file by parameter `editorCss=editor_light.css`
```css
/* editor_light.css content */
body { 
  background-color: white; 
  color: black;
}
a {
    color: blue;
}
```
The modifications works by css styling.

Is there some configuration possibility to change the color of the Title? Because it has default color blue, which is not visible on the default dark background.
Similar problem is search field. If I start typing to the search field, the default color is always black, which is not visible in the dark field.
